### ISSUE TITLE
Optimizer gate on /api/feedback/health returns all-nulls: async Supabase client yields an un-awaited coroutine

### ISSUE THREAD

**Issue by enunezvn** [enunezvn/e2i_causal_analytics#1681]
## Live defect

`GET /api/feedback/health` returns the optimizer gate block with **every value null** and an exception string in `reason`:

```json
"reason": "Optimizer gate status unavailable ('coroutine' object has no attribute 'data')",
"trainset_examples": null, "positive_signals": null, "negative_signals": null,
"total_signals": null, "would_trigger": null, "min_trainset_examples": 40
```

`FeedbackLearning.tsx:498` renders `{trainset_examples ?? '—'} / {min_trainset_examples}`, so the operator card shows **`— / 40`** plus the raw exception where `30 / 40` belongs. The optimizer half of the loop is unreadable.

## Cause

`src/api/routes/feedback.py:1176` builds its client with `get_async_supabase_client()` and passes it down through `get_optimizer_gate_status` → `read_optimizer_signal_pool` → `SignalCollectorAdapter.get_signals_for_optimization`.

That method ran `query.execute()` inside `run_in_executor`. Correct for a **sync** client, whose `execute()` blocks on HTTP and would otherwise stall the event loop. An **async** client's `execute()` returns a *coroutine*, and `run_in_executor` hands it back unawaited — so `response.data` reads an un-awaited coroutine and raises.

Isolated by running both clients against the same function in the prod container:

| client | result |
|---|---|
| `AsyncClient` (what the route passes) | all null, coroutine error |
| sync `Client` | `Insufficient trainset: 30 < 40 examples`, 30 / pos 15 / neg 61 / total 224 |

## Not caused by #1679

#1679 renamed the gate fields and changed neither the client nor this adapter; with a working client its logic produces exactly the intended output. I attributed the breakage to it before reading the diff — that was wrong.

#1668's `strict=True` did not cause it either. It **exposed** it, which is what it was added to do: before `strict`, the adapter swallowed the failure and returned `[]`, which would have published a fabricated `0` on a health surface — indistinguishable from a genuinely empty corpus.

## How it survived two "live verifications"

WAVE-12 and WAVE-13 both recorded this surface as live-verified. Those checks called `get_optimizer_gate_status` **directly with a sync client**, never through the HTTP route. And the WAVE-13 HTTP probe reported 7/7 PASS because it asserted the new field *names* were present and the old ones gone — both true while every *value* was null.

A rename is visible in the keys; a dead read only in the values. **The surface includes which client the request path constructs, not just the URL.**

## Fix

Keep the executor offload, and await the result when it is awaitable. Constructing a coroutine in a worker thread neither runs it nor binds it to a loop, so it is awaited on the request's own loop, where the client's httpx session lives.

Covered red-first in `tests/unit/test_rag/test_signals_async_client_1681.py`, asserting **values, not keys**, with the sync case as an in-file positive control (it passes before the fix, so the test cannot be trivially satisfied) and a third test guarding the regression the obvious fix would introduce — simply awaiting `execute()` fixes the async client while silently moving the sync client's blocking call onto the loop thread.

**Comment by enunezvn** [comment]
## LIVE-VERIFIED on `66217c063` (PR #1682)

`GET /api/feedback/health` → `optimizer`, in production now:

```json
{"governing_phase": "pattern", "trainset_examples": 30, "min_trainset_examples": 40,
 "positive_signals": 15, "negative_signals": 61, "total_signals": 224,
 "reason": "Insufficient trainset: 30 < 40 examples", "would_trigger": false,
 "last_trainable_signal_at": "2026-08-08T07:09:02.686027+00:00", "optimization_runs": 0}
```

The card renders **`30 / 40`** instead of `— / 40`, and the verdict, class split and denominator are all readable again.

## The verification is trustworthy this time, and here is why

The probe was run against **broken production first** and had to fail. It did — **2/7**, with all five `#1681` assertions failing on the exact all-null response. The same probe scores **7/7** after the deploy.

| assertion | broken prod | after deploy |
|---|---|---|
| no coroutine error in `reason` | FAIL | PASS |
| every published count is a real number | FAIL | PASS |
| values match the branch measurement (30/40, pos 15, total ≥224) | FAIL | PASS |
| `would_trigger` is a real boolean | FAIL | PASS |
| fix present in the running image (content, not tag) | FAIL | PASS |

Every assertion is on a **value**, and the counts are pinned to measured numbers rather than "not null" — "not null" would pass on a fabricated `0`, which on a counted health surface is the defect #1661/#1668 exist to forbid.

That negative control is exactly what the predecessor probe lacked: it reported **7/7 PASS on this dead endpoint** because it asserted the new field *names* existed and the old ones were gone — both true while every value was null. A rename is visible in the keys; a dead read only in the values. A check that has never been shown to fail is not evidence.

Two prior "live verifications" of this surface also missed it because they called `get_optimizer_gate_status` **directly with a sync client**, never through the route. **The surface includes which client the request path constructs, not just the URL.**

## Guards added

`tests/unit/test_rag/test_signals_async_client_1681.py` — 4 tests, PASSED in CI's `Heavy Unit Tests` lane:

- parametrized async/sync, where the **sync case passes before the fix** as an in-file positive control, so the pair cannot be satisfied by a merely-broken test;
- a fabricated-zero guard (`strict=False` previously returned `[]`);
- an event-loop-offload guard: naively `await`-ing `execute()` repairs the async client while silently moving the sync client's blocking call onto the loop thread — only this test catches that.
